### ISSUE TITLE
about .env

### ISSUE THREAD

**Issue by nadz-goldman** [catchain/tonscan#15]
Hi
Give,please, some description about .env
What does means sentry and what is lite ? Liteclient?
This repo only for ton? For freeton? Everscale?

**Comment by ingria** [comment]
Hi, please refer to the [config.js](https://github.com/catchain/tonscan/blob/6eb91ff8b70e9459e26a11577ad0257c6f7bc08e/src/js/config.js) file for .env variables description.

Sentry is an error collecting service (sentry.io)

This explorer is for TON (ton.org), but can be used for any blockchain, as long as `LITE_API_ENDPOINT` complies with [ton-http-api](https://github.com/toncenter/ton-http-api) response schema.
