### ISSUE TITLE
The contract appears as a .ton domain even if it is not part of .ton domain zone

### ISSUE THREAD

**Issue by Arseny271** [catchain/tonscan#26]
### Bug Type

UI

### Reproduction steps

1. Deploy a smart contract that implements the TON DNS standard

Example: https://tonscan.org/address/EQCkvks2A9kMO-7klPgwXn_M9jKyxqvcC2Y5TqAo3B8svRGN

This bug opens up opportunities for scamming. (For example, selling fake domains)

### Actual result

The contract will appear as **domainname.ton**

![image](https://user-images.githubusercontent.com/56611696/190641831-2713b8c1-be99-40a4-ac32-e7b680a811fd.png)

### Expected result

The user is expected to be notified that the contract is not a real domain in the .ton domain zone

### Suggested Severity

Medium

### Device

All browsers

**Comment by ingria** [comment]
Thank you for the report!
