### ISSUE TITLE
Wrong domain status

### ISSUE THREAD

**Issue by zmxv** [catchain/tonscan#28]
### Bug Type

Functional

### Reproduction steps

1. Visit https://tonscan.org/address/EQBX9yonQV8hyDY3j70eaTIydF8mxdL_blnOVJ4xM6es2TkD

### Actual result

<img width="1407" alt="Screen Shot 2022-09-16 at 9 21 16 PM" src="https://user-images.githubusercontent.com/363061/190648683-a7d2c0d5-faa5-43b9-81f4-010232abb9ee.png">

### Expected result

The auction has already ended (see https://dns.ton.org/#broadcaster).
Tonscan should not show that the domain is open for auction.

### Suggested Severity

High

### Device

Desktop (please complete the following information):
- OS: macOS
- Browser: Chrome
- Version: 105

**Comment by ingria** [comment]
Thank you for your input, we're merging this issue with https://github.com/catchain/tonscan/issues/39.
