### ISSUE TITLE
Some NFT's are not loaded on NFT collection page

### ISSUE THREAD

**Issue by threej-in** [catchain/tonscan#29]
### Bug Type

Functional

### Reproduction steps

Visit 
- https://tonscan.org/nft/EQC-iX44vIU2BGX_GD30Os1L3TOpTdM1jPSRrQPAhm3nJyTg
OR
- https://tonscan.org/nft/EQD7Qtnas8qpMvT7-Z634_6G60DGp02owte5NnEjaWq6hb7v

### Actual result

Some NFT cards are broken and error is logged on the console.
![image](https://user-images.githubusercontent.com/55188975/190650616-7a210466-d744-4fa2-8f69-fc8ef0d94855.png)
![image](https://user-images.githubusercontent.com/55188975/190650815-ee991888-02c0-4316-8b31-1f58f0bba9e2.png)

### Expected result

It should specify or completely hide the card if img is not available to show.

### Suggested Severity

Low

### Device

Desktop (please complete the following information):
- OS: [Windows]
- Browser [Brave]
- Version [v1.43.93]

**Comment by ingria** [comment]
Thank you for your input. This problem is caused by faulty API, so we're merging this issue with https://github.com/catchain/tonscan/issues/39.
