### ISSUE TITLE
Inconsistent domain contract types

### ISSUE THREAD

**Issue by zmxv** [catchain/tonscan#30]
### Bug Type

Functional

### Reproduction steps

1. Visit https://tonscan.org/address/EQDyK-8Mgl1rXYnI9BIoi997q8U3N9e_uhoiVe7xWXIdZmXD (contract of pool.ton)
2. Visit https://tonscan.org/address/EQBX9yonQV8hyDY3j70eaTIydF8mxdL_blnOVJ4xM6es2TkD (contract of broadcaster.ton)
3. Compare the contract types.

### Actual result

<img width="1381" alt="Screen Shot 2022-09-16 at 9 31 59 PM" src="https://user-images.githubusercontent.com/363061/190651202-6160d0ad-94b4-46b2-8166-c42665306ca1.png">

<img width="1407" alt="Screen Shot 2022-09-16 at 9 21 16 PM" src="https://user-images.githubusercontent.com/363061/190651250-5f4b1763-b98e-4c7d-a1b4-964f60867cc6.png">

### Expected result

Both contracts should be recognized as .ton domain contracts.

### Suggested Severity

High

### Device

Desktop (please complete the following information):
- OS: macOS
- Browser: Chrome
- Version: 105

**Comment by ingria** [comment]
Thank you for your input, we're merging this issue with #39.
