### ISSUE TITLE
Consistently failing to load certain NFT items

### ISSUE THREAD

**Issue by zmxv** [catchain/tonscan#31]
### Bug Type

UI

### Reproduction steps

1. Visit https://tonscan.org/nft/EQD7Qtnas8qpMvT7-Z634_6G60DGp02owte5NnEjaWq6hb7v

### Actual result

The first NFT item always fails to load even if the "Try again" button is clicked or the page is reloaded.

<img width="1409" alt="Screen Shot 2022-09-16 at 9 52 25 PM" src="https://user-images.githubusercontent.com/363061/190655258-8869e42a-a9e4-4218-a624-462e20419aee.png">

### Expected result

All NFT items should load.

### Suggested Severity

High

### Device

Desktop (please complete the following information):
- OS: macOS
- Browser: Chrome
- Version: 105

### Additional Context

The NFT in question seems to be inactive (https://tonscan.org/address/EQDSnCuPTa73vLR91L1pfy32ivel-jCulWFMQp40cARgXtCW). Anyhow, it should not be shown as a persistent error.

**Comment by ingria** [comment]
This happens when NFT numeration in collection starts with 1 instead of 0, as it should.
