### ISSUE TITLE
Fail to find .ton NFTs

### ISSUE THREAD

**Issue by zmxv** [catchain/tonscan#34]
### Bug Type

Functional

### Reproduction steps

1. Visit https://tonscan.org/address/EQBer9OO72xjjbqbVT_8clEBd9eLX90T51f574KiHpCNWVYq
2. Switch to NFTs.

### Actual result

<img width="1342" alt="Screen Shot 2022-09-16 at 10 23 28 PM" src="https://user-images.githubusercontent.com/363061/190661844-bb91c9cc-ce39-466d-950a-7055393dffa4.png">

### Expected result

The address EQBer9OO72xjjbqbVT_8clEBd9eLX90T51f574KiHpCNWVYq owns the domains spsp.ton (https://dns.ton.org/#spsp) and trinity.ton (https://dns.ton.org/#trinity). Both should be listed under the NFTs tab.

### Suggested Severity

High

### Device

Desktop (please complete the following information):
- OS: macOS
- Browser: Chrome
- Version: 105

**Comment by ingria** [comment]
Duplicate #33
