### ISSUE TITLE
Can't search domain name in .ton format

### ISSUE THREAD

**Issue by captainmarshin** [catchain/tonscan#35]
### Bug Type

UI

### Reproduction steps

1. Open tonscan.org
2. Type any domain name in search field in .ton format (for ex: wallet.ton)
3. Get error

Search working if:
4. Resize browser window or open tonscan.org from mobile browser
5. Enter domain again
6. Get searched domain
7. Resize browser window back
8. Search now working on this domain

### Actual result

Get error: Domain misconfigured or does not exist

![Screen Shot 2022-09-17 at 3 01 05 AM](https://user-images.githubusercontent.com/67394582/190832478-fd0b6761-aca3-4fb8-a480-2f237a7c6776.png)
![Screen Shot 2022-09-17 at 2 59 52 AM](https://user-images.githubusercontent.com/67394582/190832481-f333dafa-448a-4dd1-93a5-a0abb6383345.png)

### Expected result

Show searched domain name.

### Suggested Severity

Medium

### Device

Desktop (please complete the following information):
- OS: macOS High Sierra 10.13.6
- Browser: Chrome
- Version: 105.0.5195.102

**Comment by ingria** [comment]
Thank you for your input, we're merging this issue with #39.
