### ISSUE TITLE
Jetton data is not displayed

### ISSUE THREAD

**Issue by data-will-be-here** [catchain/tonscan#40]
### Bug Type

Functional

### Reproduction steps

1. Open https://tonscan.org/jetton/EQCE0Em6PpAUzfDiV66DvzTWnYLpVyn-hJHsGE6CR-L82Jxx

### Actual result

> Name not loaded
No description
![image](https://user-images.githubusercontent.com/85282394/190888092-93634a6c-c685-4830-a9d3-e3fd40a4df24.png)

### Expected result

Explorer must provide actual information. See https://tonapi.io/jetton/EQCE0Em6PpAUzfDiV66DvzTWnYLpVyn-hJHsGE6CR-L82Jxx
![image](https://user-images.githubusercontent.com/85282394/190888097-2259fbd7-6aa0-49db-832b-e31d35bcef8a.png)

### Suggested Severity

High

### Device

Desktop (please complete the following information):
- any

**Comment by ingria** [comment]
Duplicate #23
