### ISSUE TITLE
Some NFT images are not displayed in the NFT tab catalog

### ISSUE THREAD

**Issue by polivalovo** [catchain/tonscan#42]
### Bug Type

Functional

### Reproduction steps

Preconditions:

- The users in the catalog has nft from the TON Planets collection

Steps:

1. Open https://tonscan.org/
2. Add wallet address to the field 'Enter TON address' and press 'Enter'
3. Click on tab 'NFTS'
4. Scroll down till NFT with nft collection text 'Welcome to TON planet'
5. Pay attention on the screen

### Actual result

The user sees an image of their NFT
![ton6](https://user-images.githubusercontent.com/113595969/190912460-73f02bd0-4eab-4b6e-91da-893eeca5f588.png)
![ton66](https://user-images.githubusercontent.com/113595969/190912463-65fe5dff-8aad-4e0f-bfd3-667e765e3939.png)
![ton656](https://user-images.githubusercontent.com/113595969/190912465-26a71081-e778-4304-b974-8b07c9fd06a2.png)

### Expected result

White background displayed instead of image.

### Suggested Severity

Low

### Device

Device
Desktop (please complete the following information):
OS: [Windows]
Browser [chrome]
Version [105.0.5195.127]

### Additional Context

The bug reproduced on three different addresses

If user move to the NFT page, the image will be displayed on NFT page

**Comment by ingria** [comment]
Please provide the exact URL with the error.

**Comment by polivalovo** [comment]
> Please provide the exact URL with the error.

_Hello @ingria , all requested info is added below:_

https://tonscan.org/address/EQB30WNRaxd1LKBklZ32emN6o4s_v2zNFaIuOGerrf9l-EWL
https://tonscan.org/address/EQD8FusKaTMEBz6PQkUUQmfTg9hcRWDSO1z4QLCLQV2rdX1k
https://tonscan.org/address/EQBJ5m6Egvil4EVwCNNs4AjbeBsvUme1qgZbe-70-hGKCDnZ

**Comment by ingria** [comment]
Thanks! This is the same problem as described in #37. Closing this one as dupe.
