### ISSUE TITLE
The hash from the backend is displayed differently on the frontend in the "History" table

### ISSUE THREAD

**Issue by prafair** [catchain/tonscan#44]
### Bug Type

UI

### Reproduction steps

Case 1 (with slash):
1. Open this address https://tonscan.org/address/EQA1nVcPqLmrCBsD7OvuJ4QUCBV9VUWhKiA2VYoNgE2_na-g
2. Click on a row with underscore character in the hash

Case 2 (with plus):
1. Open this address 
2. Click on a row with minuses in the hash

### Actual result

Case 1.
The hash with underscore, but on the backend without underscore:

<img width="1792" alt="bug_tonscan_hash_actual_result" src="https://user-images.githubusercontent.com/15040493/191047736-c418a834-c3a5-47fe-8634-7a1e22b9946b.png">

Case 2.
The hash with minus, but on the backend without minus:

<img width="1792" alt="bug_tonscan_plus_actual_result" src="https://user-images.githubusercontent.com/15040493/191102593-f9d4d3ff-a0c5-4cc5-bc57-eeca5b6028f7.png">

### Expected result

Case 1.
The hash must be with a slash, as on the backend (for example, if you reveal detailed information):

<img width="1792" alt="bug_tonscan_hash_expected_result" src="https://user-images.githubusercontent.com/15040493/191049069-2175015a-b396-4192-b79e-5f3e462e7936.png">

Case 2.
The hash must be with a plus, as on the backend (for example, if you reveal detailed information):

<img width="1791" alt="bug_tonscan_plus_expected_result" src="https://user-images.githubusercontent.com/15040493/191103138-4ca2f1e7-4854-486c-ae4e-55f4383ac343.png">

### Suggested Severity

Medium

### Device

Desktop:
- **OS**: macOS Big Sur (11.6.1)
- **Browser**: Chrome
- **Browser version**: 105.0.5195.125 (x86_64)

### Additional Context

After some investigation, I may be guessing that there is can be different behaviour in `getTransactions` function
(https://github.com/catchain/tonscan/blob/master/src/js/api.js#L58) and `getTransaction` function (https://github.com/catchain/tonscan/blob/master/src/js/api.js#L103).

There is a feeling that as if the code in the repository has not been updated. For example, I didn't find any new API methods (for example, `getTransactionsByAddress`). And so it's harder to guess what could have gone wrong.

**Comment by ingria** [comment]
Both variants (`/+` and `-_`) [are valid](https://en.wikipedia.org/wiki/Base64#Variants_summary_table), the difference is purely cosmetic. We use the latter format in URLs, because it looks nicer (it doesn't need to be [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding)).

This is something like `е` and `ё` letters in russian - in some words they are interchangeable.
