### ISSUE TITLE
Contract tab is not working

### ISSUE THREAD

**Issue by v4n3k4** [catchain/tonscan#47]
### Bug Type

Functional

### Reproduction steps

Precondition: User should have an available TON wallet address
1. Go to https://tonscan.org/
2. Enter your TON address
3. Click on "Contract"

### Actual result

Infinity loading appears after clicking on "Contract". Status 500 appears for "source" GET request

### Expected result

"Contract" tab is working

### Suggested Severity

Medium

### Device

Desktop:
- OS: macOS Monterey
- Browser: Brave
- Version: v1.43.93

Smartphone:
- Device: iPhone 7
- OS: iOS 14.2
- Browser: Brave
- Version: 1.42

### Additional Context

<img width="1280" alt="Screenshot 2022-09-21 at 00 10 56" src="https://user-images.githubusercontent.com/60569564/191374456-37be820d-62c8-4f58-8919-cd4653ff7761.png">
<img width="800" alt="Screenshot 2022-09-21 at 00 16 45" src="https://user-images.githubusercontent.com/60569564/191374471-04222c0f-fd1b-4ccb-8296-56f275faf9bc.png">

**Comment by ingria** [comment]
Duplicate #41
