### ISSUE TITLE
Not all NFTs' icons displayed while scrolling the collection.

### ISSUE THREAD

**Issue by Reveloper** [catchain/tonscan#51]
### Bug Type

Functional

### Reproduction steps

1. Open any collection via Tonscan explorer ([Ton Punks](https://tonscan.org/nft/EQAo92DYMokxghKcq-CkCGSk_MgXY5Fo1SPW20gkvZl75iCN) as example).
2. Scroll down and look through collection items.

### Actual result

Some of NFTs' icons couldn't display. These icons are impossible to see until the whole page will be refresh.
![image](https://user-images.githubusercontent.com/39581753/191718089-95993a3a-6df8-4435-b555-c6328ac08667.png)

![nft lost pic](https://user-images.githubusercontent.com/39581753/191717747-4963b9d5-8a5b-44f1-8545-f5eeef4b74fc.png)

### Expected result

Display all NFTs' icons of collection.

### Suggested Severity

Medium

### Device

Desktop 1:
OS: Windows 10 Pro
Browser Google Chrome
Version 105.0.5195.127

Desktop 2:
OS: macOS 12.2.1
Browser Safari

Smartphone 1:
Device: Samsung Galaxy M31
OS: Android 12
Samsung Internet
Version 18.0.058

Smartphone 2:
Device: iPhone 12
OS:  iOS 15.6.1
Browser Safari
Version 15.6.1

### Additional Context

1.Records from test environments.

Microsoft Windows test video:

https://user-images.githubusercontent.com/39581753/191714153-43005664-360f-460a-9793-28d162650269.mov

MacOS test video:

https://user-images.githubusercontent.com/39581753/191714236-d820e88b-1150-4c91-85db-d65b9538cc7f.mov

Android test video:

https://user-images.githubusercontent.com/39581753/191714021-996288b0-3a3b-45e8-9b1e-628620aab850.mov

iOS test video:

https://user-images.githubusercontent.com/39581753/191713852-92236f14-2b69-4153-a991-e2b2887b2c95.mov

2. Additional note.
Sometimes(it looks like on the screenshot below) the user has an option for reloading but it looks not user-friendly when you look through thousands of pictures and have to push the button to refresh every lost pic.
![nft unloaded](https://user-images.githubusercontent.com/39581753/191715004-19bc8391-f7d3-4211-a0b5-ed9ed7af2f55.png)

**Comment by ingria** [comment]
You can reload the image using its context menu:

https://user-images.githubusercontent.com/2178368/196212990-663fc989-67de-436c-8af8-782aa738876c.mp4
