### ISSUE TITLE
Duplicates and lost NFT items on the NFT collection tab.

### ISSUE THREAD

**Issue by Reveloper** [catchain/tonscan#52]
### Bug Type

Functional

### Reproduction steps

1. Open any collection via Tonscan explorer ([Ton Whales](https://tonscan.org/nft/EQDvRFMYLdxmvY3Tk-cfWMLqDnXF_EclO2Fp4wwj33WhlNFT) or [Ton Diamonds](https://tonscan.org/nft/EQAG2BH0JlmFkbMrLEnyn2bIITaOSssd4WdisE4BdFMkZbir) as an example).
2. Scroll down and look through collection items.

### Actual result

Almost every time you look through one collection you will get at least one duplicate item and one will be lost.

![image](https://user-images.githubusercontent.com/39581753/191732022-d03b0986-9035-43fd-9f4a-8ca6c480c1a9.png)
![image](https://user-images.githubusercontent.com/39581753/191732048-a8eabce6-a762-4c95-ad62-daac41f6f203.png)
![image](https://user-images.githubusercontent.com/39581753/191732100-a6013d3a-25cb-4fd5-aade-12ac40cbc116.png)
![image](https://user-images.githubusercontent.com/39581753/191732253-4fdccdcd-c3ba-4091-937b-67a14fb32fb7.png)

### Expected result

Looking through the whole collection without any duplicates or lost NFT.

### Suggested Severity

Critical

### Device

Desktop (please complete the following information):
OS: Windows 10 Pro
Browser Google Chrome
Version 105.0.5195.127

### Additional Context

Perhaps, this behavior has a connection with how the offset is requested. For example, when I've got duplicates in the Ton Whales list,
![image](https://user-images.githubusercontent.com/39581753/191733199-2d7321c7-191e-44e8-9972-3e1fda30339e.png)
query history was like
![image](https://user-images.githubusercontent.com/39581753/191733054-a1b2c5de-4c22-45a6-92c3-55963b3757cf.png)

Response bodies for 60-82 items:
[response content.zip](https://github.com/catchain/tonscan/files/9625214/response.content.zip)

Video:

https://user-images.githubusercontent.com/39581753/191735269-92d5fc03-330b-4db3-9625-b72a54b2d9c6.mov

**Comment by Reveloper** [comment]
Dear Tonscan team, 
is it true, that such issue does not equal bug or minor bug for You? I decided to clarify, because It looks like you have not time to check last 3-4 issues or something else reason they unmarked. If it is really unrelevant issue(or is not a bug), please, let us know with your marks, as it was for all other issues.

**Comment by ingria** [comment]
Thank you for your input. Ton hackaton has ended, so there's no need to label issues anymore.
