### ISSUE TITLE
Unable to get contract info on testnet

### ISSUE THREAD

**Issue by shuva10v** [catchain/tonscan#55]
### Bug Type

Functional

### Reproduction steps

1. Open https://testnet.tonscan.org/
2. Search for any contract, like [EQAK8C7Jv9RBWLLGM1J4-MJttkfSGLQva8oL-fG45UKAb3Ud](https://testnet.tonscan.org/address/EQAK8C7Jv9RBWLLGM1J4-MJttkfSGLQva8oL-fG45UKAb3Ud)
3. You will get empty value for contact type, also Contract tab is empty
![TON Explorer :: EQAK8C7Jv9RBWLLGM1J4-MJttkfSGLQva8oL-fG45UKAb3Ud 2022-11-01 12-06-17](https://user-images.githubusercontent.com/1140437/199199120-0e01a07e-f11b-4ecb-bf28-8f9058001aaa.jpg)

It looks like actual backend - https://testnet.api.ton.cat/ - is failed to provide results, it returns  net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH. May be SSL issue...

### Actual result

Info about contracts on testnet is failed to load

### Expected result

Info about contracts

### Suggested Severity

Medium

### Device

Desktop (please complete the following information):
- OS: macOS
- Browser: Chrome, Safari

**Comment by ingria** [comment]
Thanks for the report!
