### ISSUE TITLE
Inconsistent Tonscan data

### ISSUE THREAD

**Issue by emiliana32** [catchain/tonscan#67]
Good morning,
one of the key feature of a blockchain is that it is transparent and can be analysed by anyone. However, in the case of the TON blockchain, which is in the top 15 according to CMC, and from a technological point of view is the most promising one, it seems impossible to know what the statistics are.
[CMC](https://coinmarketcap.com/currencies/toncoin/)
-Circulating Supply: 3,431,892,088
-Total Supply: 5,047,558,528
[Tonscan](https://tonscan.org/stats)
-Circulating Supply: 3,414,166,606
-Total Supply: 5,047,558,528
[Tontech](https://tontech.io/stats/)
-Circulating Supply: 3,436,986,739
-Total Supply: 5,089,155,274
[TonStat](https://www.tonstat.com/)
-Circulating Supply: ?
-Total Supply: 5,089,086,273[
CG](https://www.coingecko.com/en/coins/toncoin)
-Circulating Supply: 1,473,591,410
-Total Supply: 5,057,362,773
Is anyone able to explain the reason for these inconsistencies, despite the source being the same and transparent?
Thank you

**Comment by tonscan** [comment]
The data has been updated, the current values ​​are correct.

https://tonscan.org/stats

**Comment by emiliana32** [comment]
Hello,
I have found another data inconsistency. Please let me know if it is better to open a new issue.
[Tonscan](https://tonscan.org/stats) stake 518 M
[TonTech](https://tontech.io/stats/) stake 275.43
[TonStat](https://www.tonstat.com/) stake 489 M
Which one is correct? I suppose the value is calculated in different ways.
Thank you

**Comment by tonscan** [comment]
Tonscan calculates the total stake of validators of the current round and the frozen stakes of validators from the previous round, which are stored on the [Elector address](https://tonscan.org/address/Ef8zMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzM0vF). Tontech displays the stake of validators only for the current round, without taking the frozen part into account. I'm sorry, but I am not familiar with the methodology or tonstats.

**Comment by emiliana32** [comment]
Thank you for the quick reply. I think it would be clearer if you specify the number of validators for both rounds, since the most important round is the current one. In the meantime, I will try to reach tonstats.

**Comment by tonscan** [comment]
We are preparing to launch a new page with a list of validators, it will be available soon.

**Comment by emiliana32** [comment]
> We are preparing to launch a new page with a list of validators, it will be available soon. Probably we also add a list of validators from the previous round on it.

This is extremely positive news for the transparency of the ecosystem.

**Comment by emiliana32** [comment]
Hi,
after the [TBF](https://tonviewer.com/EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2) the circulating supply of TON needs to be updated. Only a few statistics websites have been updated at the moment:
[CMC](https://coinmarketcap.com/currencies/toncoin/)
-Circulating Supply: 3,431,892,088->wrong
-Total Supply: 5,047,558,528
[Tonscan](https://tonscan.org/stats)
-Circulating Supply: 3,414,166,606->wrong
-Total Supply: 5,097,723,915
[Tontech](https://tontech.io/stats/)
-Circulating Supply: 2,135,539,595->correct
-Total Supply: 5,097,723,876
[TonStat](https://www.tonstat.com/)
-Circulating Supply: ?
-Total Supply: 5,097,660,342
[CG](https://www.coingecko.com/en/coins/toncoin)
-Circulating Supply: 2,135,539,595->correct
-Total Supply: 5,097,775,794
[Tonviewer](https://tonviewer.com/price)
-Circulating Supply: 2,135,540,121->correct
-Total Supply: ?
So I think tonscan should update them accordingly.
