### ISSUE TITLE
tonscan.org suddenly shows garbage instead of timestams

### ISSUE THREAD

**Issue by esigra** [catchain/tonscan#79]
### Bug Type

Localization

### Reproduction steps

I used tonscan.org for several months and it showed timestamps like 2023-07-23 15:32:48 that can be copied and pasted into spreadsheets. But some time today it stopped showing it. Instead it shows some garbage like Oct 19, 2023, 07:40 PM. That string is much harder to interpret (seconds are missing completely!) and breaks sorting of dates.

The site has no documentation so I can not read what settings are needed in the browser to get proper timestamps from tonscan.org.

### Actual result

Oct 19, 2023, 07:40 PM

### Expected result

2023-10-19 19:40:??

### Suggested Severity

High

### Device

Desktop:
- Microsoft Windows
- Chrome
- Version 118.0.5993.88

Also tested on Firefox/Linux but the timestamps never worked there.

**Comment by ingria** [comment]
What browser are you using and what page are you referring to?

**Comment by esigra** [comment]
For example this: https://tonscan.org/address/EQAwsDboFl_iGuaflNn5959HOamenkvQEQDwakO55CY2SGB8
Click on a transaction to expand it and look below the text "Timestamp".

**Comment by esigra** [comment]
I see that the code calls toLocaleString in 5 places: https://github.com/search?q=repo%3Acatchain%2Ftonscan+toLocaleString&type=code

In one of them, it adds the parameter this.$i18n.locale. I do not know why it does it in only one of the places. I do not know whether a localized string is sent from the server to the browser or if it is localized in the browser.

**Comment by ingria** [comment]
The code in this repository is a bit outdated, but yes, dates are created locally with `toLocaleString` method. We'll add seconds to transaction dates in the next release.

Meanwhile, could you tell me what is your browser active locale (type `navigator.language` in console)?

**Comment by esigra** [comment]
Microsoft Windows: 'sv'
Linux: "sv-SE"

**Comment by ingria** [comment]
Ok, thanks. So the problem here is that we're using the american date format to display the date, and therefore it looks strange for someone outside the US. 

We'll think how to fix that, thanks for the report.

**Comment by esigra** [comment]
Thanks, timestamps work again on Microsoft Windows (but still on Linux) so all is the same as a few days ago.
