### ISSUE TITLE
GIF NFT

### ISSUE THREAD

**Issue by Vudi** [catchain/tonscan#8]
You are not displaying NFT GIFs.

Example: https://tonscan.org/nft/EQB4H3VygP7Y7PUMJdL10duuvGiCjB1qJ8oaLbFjVSA5PL0K

**Comment by KARP-2022** [comment]
Мои NFT отображаются, например, тут 
https://map.tonearth.com/ru/owner.php?wallet=EQBRybaa-aS69wvdp2q_-HuREP698Rw0p_5wfZ0q7iUjFdQ4

**Comment by ingria** [comment]
There's a problem with GIFs: they are enormous. Displaying them "as is" would be too traffic consuming for users, and resizing/converting them would be too resource consuming for our servers.

As a compromise, we've decided to only display GIFs that could be resized and converted without melting down our servers. For now, such GIFs should be 40 megapixels or less.
