### ISSUE TITLE
tonscan.org no longer shows domain names in From and To fields after switch from EQ to UQ

### ISSUE THREAD

**Issue by esigra** [catchain/tonscan#82]
### Bug Type

Functional

### Reproduction steps

Look at any wallet at tonscan.org.

### Actual result

Only addresses are shown in the From and To fields.

### Expected result

Domain names are shown instead of addresses when they exist.

### Suggested Severity

Medium

### Device

Linux and Microsoft Windows.

### Additional Context

It may be because addresses are shown starting with UQ instead of EQ. Maybe it will be fixed when everyone has somehow reassigned their domain name to the UQ version of the address. But it would be better if it just worked immediately.

**Comment by ingria** [comment]
Fixed, thanks for the report
